-- Multi-tenancy (Pool model): global tenants catalogue.
-- Numeric surrogate key generated as an identity column (maps to JPA GenerationType.IDENTITY).
CREATE TABLE tenants (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    slug        VARCHAR(100) NOT NULL UNIQUE,
    plan        VARCHAR(20)  NOT NULL DEFAULT 'STANDARD',
    max_users   INT          NOT NULL DEFAULT 50,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    is_platform BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Reserved tenants with fixed identifiers:
--  * id=1 platform: the SaaS provider plane (PLATFORM_ADMIN users), runs outside tenant scope.
--  * id=2 legacy:   holds all pre-existing Phase-1 data so current behaviour is preserved.
INSERT INTO tenants (id, name, slug, plan, max_users, status, is_platform) VALUES
    (1, 'Platform', 'platform', 'PREMIUM', 100, 'ACTIVE', TRUE),
    (2, 'Legacy',   'legacy',   'PREMIUM', 100, 'ACTIVE', FALSE);

-- Advance the identity sequence so auto-generated tenant ids start after the reserved ones.
ALTER TABLE tenants ALTER COLUMN id RESTART WITH 3;
